#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page
# Redirection must be a "301 Moved Permanently"

ADD301_REDIRECT="\\\tlocation /redirect_me {\n\t\t return 301 https://google.com;\n\t}\n"

sudo apt-get update
sudo apt-get -y install nginx
#sudo service nginx start
echo "Hello World" | sudo tee /var/www.html/index.html
sudo sed -i "301 &ADD301_REDIRECT" /etc/nginx/sites-available/default #add at line 30
sudo service nginx start
